### ISSUE TITLE
Netlify requires Pro for private repos

### ISSUE THREAD

**Issue by nimast** [SAIC-ATS/thewrong-2021#3]
Hey all,

I've been getting emails from Netlify, they changed the conditions of their free plan and they now require Pro for any private repos. I tried to reach out regarding educational plans but it doesn't seem straightforward. We can consider other hosting options but I wanted to ask first what do ya'll think of just open sourcing this repo?

cc @bfallc @juanedflores @macpierce 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/610091/185508814-826a8d65-87e5-4ec5-a54f-2c00ff58a1c1.png">

**Comment by bfallc** [comment]
Done.

**Comment by bfallc** [comment]
done.
